### ISSUE TITLE
prefab.js9.atyourservice.configure_portal() fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#86] opened 2017-11-22 18:00 UTC
#### Installation information

- jumpscale version:
- operating system:

Relates to https://github.com/Jumpscale/ays9/issues/378#issuecomment-346411804

#### Detailed description

```python
prefab.js9.atyourservice.configure_portal(host='http://185.193.143.74', port="5000")
```

```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 prefab.js9.atyourservice.configure_portal(host='http://185.193.143.74', port="5000")

/opt/code/github/jumpscale/prefab9/modules/js9/PrefabAtYourService.py in configure_portal(self, host, port, portal)
     30             host = "http://%s" % host
     31         config = {"ays_uri": "%s:%s" % (host, port)}
---> 32         self.prefab.web.portal.add_configuration(config)
     33         nav_path = "$JSAPPSDIR/portals/{portal}/base/AYS/.space/nav.wiki".format(portal=portal)
     34         nav = self.prefab.core.file_read(nav_path).format(ays_uri="%s:%s" % (host, port))

/opt/code/github/jumpscale/prefab9/modules/web/PrefabPortal.py in add_configuration(self, config_dict)
     56         usually when u add a new space
     57         """
---> 58         content = self.prefab.core.file_read('$TEMPLATEDIR/cfg/portal/config.yaml')
     59         cfg = j.data.serializer.yaml.loads(content)
     60         for key, value in config_dict.items():

/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py in file_read(self, location, default)
    640         if default is None:
    641             assert self.file_exists(
--> 642                 location), "prefab.file_read: file does not exists {0}".format(location)
    643         elif not self.file_exists(location):
    644             return default

AssertionError: prefab.file_read: file does not exists /opt/var/templates/cfg/portal/config.yaml
```

**Comment by khaledkbadr** [comment] 2017-11-27 14:12
Can't reproduce the issue on a clean JS#master installation. My best guess is that the path was changed and the environment is outdated.

**Comment by yveskerwyn** [comment] 2017-11-27 16:12
@khaledkbadr I just followed the steps documented in the above gist I got this when executing `prefab.js9.atyourservice.configure_portal(host='http://172.17.0.5', port="5000")`:

```python
Input                                     Traceback (most recent call last)
/usr/local/bin/js9 in <module>()
----> 1 prefab.js9.atyourservice.configure_portal(host='http://172.17.0.5', port="5000")

/opt/code/github/jumpscale/prefab9/modules/js9/PrefabAtYourService.py in configure_portal(self, host, port, portal)
     30             host = "http://%s" % host
     31         config = {"ays_uri": "%s:%s" % (host, port)}
---> 32         self.prefab.web.portal.add_configuration(config)
     33         nav_path = "$JSAPPSDIR/portals/{portal}/base/AYS/.space/nav.wiki".format(portal=portal)
     34         nav = self.prefab.core.file_read(nav_path).format(ays_uri="%s:%s" % (host, port))

/opt/code/github/jumpscale/prefab9/modules/web/PrefabPortal.py in add_configuration(self, config_dict, name)
     58         usually when u add a new space
     59         """
---> 60         cfg = self.prefab.executor.state.configGet('portal')
     61         for key, value in config_dict.items():
     62             cfg[name][key] = value

/opt/code/github/jumpscale/core9/JumpScale9/core/State.py in configGet(self, key, defval, set)
     55
     56     def configGet(self, key, defval=None, set=False):
---> 57         return self._get(key=key, defval=defval, set=set, config=self._configJS, path=self.configJSPath)
     58
     59     def configSet(self, key, val, save=True):

/opt/code/github/jumpscale/core9/JumpScale9/core/State.py in _get(self, key, defval, set, config, path)
     88                 raise j.exceptions.Input(
     89                     message="could not find config key:%s in executor:%s" %
---> 90                     (key, self), level=1, source="", tags="", msgpub="")
     91
     92     def _set(self, key, val, save=True, config=None, path=""):

Input: ERROR: could not find config key:portal in executor:{'ays': {'production': True, 'oauth': {'redirect_uri': 'https://locahost:5000', 'jwt_key': 'MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n27MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny66+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv', 'client_secret': '', 'client_id': '', 'organization': 'ays-server-clients-org'}}, 'system': {'container': False, 'autopip': '0', 'readonly': False, 'debug': True}, 'redis': {'port': 6379, 'enabled': False, 'addr': 'localhost'}, 'plugins': {'JumpScale9': '/opt/code/github/jumpscale/core9/JumpScale9/', 'JumpScale9Lib': '/opt/code/github/jumpscale/lib9/JumpScale9Lib', 'JumpScale9Prefab': '/opt/code/github/jumpscale/prefab9/JumpScale9Prefab'}, 'dirs': {'TEMPLATEDIR': '/opt/var/templates', 'BUILDDIR': '/opt/var/build', 'LOGDIR': '/opt/var/log', 'DATADIR': '/opt/var/data', 'HOMEDIR': '/root', 'CODEDIR': '/opt/code', 'VARDIR': '/opt/var', 'JSAPPSDIR': '/opt/jumpscale9/apps', 'BINDIR': '/opt/bin', 'CFGDIR': '/opt/cfg', 'TMPDIR': '/tmp', 'HOSTCFGDIR': '/root/js9host/cfg/', 'BASEDIRJS': '/opt/jumpscale9', 'HOSTDIR': '/root/js9host/', 'BASEDIR': '/opt', 'LIBDIR': '/opt/lib/'}} ((type:input.error)
```

**Comment by khaledkbadr** [comment] 2017-11-28 06:58
> I just followed the steps documented in the above gist I got this when executing 

As I inspected the gist, you try to configure portal before it's been installed. That's why it's missing it the `portal` key from the config. cause it wasn't installed

**Comment by khaledkbadr** [comment] 2017-11-28 08:12
Will add a way to configure AYS API Console in #99 

This issue is not needed anymore, @yveskerwyn what do you think?

**Comment by yveskerwyn** [comment] 2017-11-28 08:15
It can be closed, but I'm wondering whether we'll still need this `configure_portal()` once you've created this new method to configure the AYS API Console independently... What is the use case for also still having 'configure_portal()' around then?

**Comment by khaledkbadr** [comment] 2017-11-28 08:27
`configure_portal` is needed for AYS url inside the portal. it has nothing to do with AYS API Console from the start

**Comment by khaledkbadr** [comment] 2017-11-28 08:28
I will close this issue in favor of #99

**Closed by khaledkbadr** 2017-11-28 08:28 UTC
Labels: priority_major, state_question, type_bug
